
version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser",
    "jest"
  ]
  plugins = ["vue"]
  module_system = "es-modules"
  dependency_file_paths = [
  "src/templates/starter-templates/Default/package.json",
  "src/templates/starter-templates/GraphQL/package.json",
  "src/templates/starter-templates/Nuxt.js/package.json",
  "src/templates/starter-templates/pwa/package.json",
  ]
